# ==============================================================================
# test_phase4.jl
#
# Phase 4 — Validation
#
# Two complementary test groups:
#
# A) REGRESSION TESTS  (require pre-generated CSV reference data)
#    Load the CSVs from test/reference_data/, re-evaluate the same inputs
#    through mfeval, and assert every output column matches within 1e-6.
#    The CSVs are generated by test/generate_reference_data.jl.
#    When MATLAB is available, regenerate the CSVs from MATLAB mfeval to
#    validate the Julia solver against the true external reference.
#
# B) EDGE-CASE & INVARIANT TESTS  (no CSV required — always run)
#    Verify physical invariants that must hold regardless of tyre version:
#    zero-Fz, standstill, locked wheel, max camber, out-of-range inputs,
#    low-speed regime, sign conventions, geometry bounds.
#
# Stand-alone usage:
#   julia --project=. test/test_phase4.jl
# ==============================================================================

if !isdefined(Main, :MFeval)
    using Test
    include(joinpath(@__DIR__, "..", "src", "MFeval.jl"))
    using .MFeval
end

# ── Fixtures ───────────────────────────────────────────────────────────────────
const _P4_FIX = joinpath(@__DIR__, "fixtures")
const _P4_REF = joinpath(@__DIR__, "reference_data")

const _p4_p61 = read_tir(joinpath(_P4_FIX, "MagicFormula61_Parameters.tir"))
const _p4_p62 = read_tir(joinpath(_P4_FIX, "MagicFormula62_Parameters.tir"))
const _p4_p52 = read_tir(joinpath(_P4_FIX, "MagicFormula52_Parameters.tir"))

const _p4_M111 = MFModes(111)

# Tolerance that matches the README spec (<1e-6 for all 30 columns)
const _P4_TOL = 1e-6

# ==============================================================================
# CSV helpers
# ==============================================================================

# Read a reference CSV -> (N x 7 input matrix, N x 30 reference output matrix).
# Returns (nothing, nothing) when the file does not exist yet.
function _load_ref(filename::String)
    path = joinpath(_P4_REF, filename)
    isfile(path) || return nothing, nothing

    lines = readlines(path)
    N = length(lines) - 1          # first line is header
    N > 0 || return nothing, nothing

    ref = Matrix{Float64}(undef, N, 30)
    for (i, line) in enumerate(lines[2:end])
        ref[i, :] = parse.(Float64, split(line, ','))
    end

    # Reconstruct inputs from pass-through columns in the CSV:
    # col 3=Fz  col 7=kappa  col 8=alpha  col 9=gamma
    # col 10=phit  col 11=Vx  col 12=pressure
    inp = hcat(ref[:, 3],   # Fz
               ref[:, 7],   # kappa
               ref[:, 8],   # alpha
               ref[:, 9],   # gamma
               ref[:, 10],  # phit
               ref[:, 11],  # Vx
               ref[:, 12])  # pressure
    return inp, ref
end

# Re-evaluate and check every column (except col 29 inst_Kya which is a
# finite-difference quantity) against the reference within _P4_TOL.
# Returns (passed::Bool, n_rows::Int).
function _check_regression(p::TireParams, filename::String,
                            modes::MFModes; tol::Float64=_P4_TOL)
    inp_mat, ref_mat = _load_ref(filename)
    inp_mat === nothing && return false, 0

    out  = mfeval(p, inp_mat, modes)
    cols = [1:28; 30]              # skip col 29 (inst_Kya)

    ok = true
    for c in cols
        maxD = maximum(abs.(out[:, c] .- ref_mat[:, c]))
        if maxD > tol
            @warn "col $c  max|D|=$maxD  tol=$tol" filename
            ok = false
        end
    end
    return ok, size(ref_mat, 1)
end

# Macro: wrap a regression check into a @testset, skipping cleanly when no CSV.
macro regression_testset(label, p, filename, modes)
    quote
        @testset $label begin
            ok, n = _check_regression($(esc(p)), $(esc(filename)), $(esc(modes)))
            if n > 0
                @test ok
            else
                @test_skip true
            end
        end
    end
end

# ==============================================================================
# A) REGRESSION TESTS
# ==============================================================================

@regression_testset "Phase 4: regression — MF6.1 pure lateral"      _p4_p61 "mf61_pure_lat.csv"   _p4_M111
@regression_testset "Phase 4: regression — MF6.1 pure longitudinal"  _p4_p61 "mf61_pure_lon.csv"   _p4_M111
@regression_testset "Phase 4: regression — MF6.1 combined slip"      _p4_p61 "mf61_combined.csv"   _p4_M111
@regression_testset "Phase 4: regression — MF6.1 camber sweep"       _p4_p61 "mf61_camber.csv"     _p4_M111
@regression_testset "Phase 4: regression — MF6.1 load sweep"         _p4_p61 "mf61_load.csv"       _p4_M111
@regression_testset "Phase 4: regression — MF6.1 pressure sweep"     _p4_p61 "mf61_pressure.csv"   _p4_M111
@regression_testset "Phase 4: regression — MF6.2 pure lateral"       _p4_p62 "mf62_pure_lat.csv"   _p4_M111
@regression_testset "Phase 4: regression — MF5.2 pure lateral"       _p4_p52 "mf52_pure_lat.csv"   _p4_M111
@regression_testset "Phase 4: regression — MF6.1 edge cases"         _p4_p61 "mf61_edge_cases.csv" _p4_M111

# ==============================================================================
# B) EDGE-CASE TESTS  (always run — no CSV required)
# ==============================================================================

@testset "Phase 4: edge case — Fz = 0" begin
    out = mfeval(_p4_p61, MFInputs(0.0, 0.0, 0.1, 0.0, 0.0, 16.6), _p4_M111)
    @test all(isfinite, to_vector(out))
    @test abs(out.Fx)  < 1.0
    @test abs(out.Fy)  < 1.0
    @test abs(out.Mx)  < 1.0
    @test abs(out.Mz)  < 1.0
    @test out.mux == 0.0
    @test out.muy == 0.0
end

@testset "Phase 4: edge case — Vx = 0 (standstill)" begin
    out = mfeval(_p4_p61, MFInputs(6752.0, 0.0, 0.0, 0.0, 0.0, 0.0), _p4_M111)
    @test all(isfinite, to_vector(out))
    @test out.My    == 0.0
    @test out.omega >= 0.0
end

@testset "Phase 4: edge case — locked wheel (kappa = -1)" begin
    out = mfeval(_p4_p61, MFInputs(6752.0, -1.0, 0.0, 0.0, 0.0, 16.6), _p4_M111)
    @test all(isfinite, to_vector(out))
    @test out.Fx < 0.0
    @test abs(out.Fx) > 1000.0
end

@testset "Phase 4: edge case — maximum camber" begin
    gamma_max = _p4_p61.cammax
    for g in (gamma_max, -gamma_max)
        out = mfeval(_p4_p61, MFInputs(6752.0, 0.0, 0.0, g, 0.0, 16.6), _p4_M111)
        @test all(isfinite, to_vector(out))
    end
end

@testset "Phase 4: edge case — inputs beyond valid range (clamped)" begin
    # alpha beyond ALPMAX
    @test all(isfinite, to_vector(
        mfeval(_p4_p61, MFInputs(6752.0, 0.0, _p4_p61.alpmax * 2.0, 0.0, 0.0, 16.6), _p4_M111)))

    # alpha at exactly ALPMAX
    @test all(isfinite, to_vector(
        mfeval(_p4_p61, MFInputs(6752.0, 0.0, _p4_p61.alpmax, 0.0, 0.0, 16.6), _p4_M111)))

    # kappa beyond KPUMAX
    @test all(isfinite, to_vector(
        mfeval(_p4_p61, MFInputs(6752.0, _p4_p61.kpumax * 1.5, 0.0, 0.0, 0.0, 16.6), _p4_M111)))

    # Negative Fz must be clamped to 0
    out_neg = mfeval(_p4_p61, MFInputs(-1000.0, 0.0, 0.1, 0.0, 0.0, 16.6), _p4_M111)
    @test all(isfinite, to_vector(out_neg))
    @test out_neg.Fz == 0.0
end

@testset "Phase 4: edge case — low-speed regime" begin
    Vlow    = _p4_p61.vxlow * 0.5
    out_low = mfeval(_p4_p61, MFInputs(6752.0, -0.1, 0.1, 0.0, 0.0, Vlow), _p4_M111)
    out_nom = mfeval(_p4_p61, MFInputs(6752.0, -0.1, 0.1, 0.0, 0.0, 16.6), _p4_M111)
    @test all(isfinite, to_vector(out_low))
    @test abs(out_low.Fx) <= abs(out_nom.Fx) + 100.0
    @test abs(out_low.Fy) <= abs(out_nom.Fy) + 100.0
end

@testset "Phase 4: edge case — no-limits mode (M211)" begin
    out = mfeval(_p4_p61, MFInputs(6752.0, -0.05, 0.1, 0.0, 0.0, 16.6), MFModes(211))
    @test all(isfinite, to_vector(out))
end

@testset "Phase 4: edge case — turn-slip mode (M112)" begin
    out = mfeval(_p4_p61, MFInputs(6752.0, 0.0, 0.1, 0.0, 0.02, 16.6), MFModes(112))
    @test all(isfinite, to_vector(out))
end

# ==============================================================================
# C) PHYSICAL INVARIANTS
# ==============================================================================

@testset "Phase 4: invariants — sign conventions (ISO-W)" begin
    Fnom = _p4_p61.fnomin
    Vnom = _p4_p61.longvl

    # Fy: positive alpha -> negative Fy (ISO-W)
    out_pa = mfeval(_p4_p61, MFInputs(Fnom, 0.0,  0.1, 0.0, 0.0, Vnom), _p4_M111)
    out_na = mfeval(_p4_p61, MFInputs(Fnom, 0.0, -0.1, 0.0, 0.0, Vnom), _p4_M111)
    @test out_pa.Fy < 0.0
    @test out_na.Fy > 0.0

    # Fx: positive kappa (drive) -> positive Fx
    out_drv = mfeval(_p4_p61, MFInputs(Fnom,  0.1, 0.0, 0.0, 0.0, Vnom), _p4_M111)
    out_brk = mfeval(_p4_p61, MFInputs(Fnom, -0.1, 0.0, 0.0, 0.0, Vnom), _p4_M111)
    @test out_drv.Fx > 0.0
    @test out_brk.Fx < 0.0

    # My: negative at forward rolling (rolling resistance)
    out_roll = mfeval(_p4_p61, MFInputs(Fnom, 0.0, 0.0, 0.0, 0.0, Vnom), _p4_M111)
    @test out_roll.My < 0.0
end

@testset "Phase 4: invariants — geometry bounds" begin
    Fnom = _p4_p61.fnomin
    Vnom = _p4_p61.longvl
    out  = mfeval(_p4_p61, MFInputs(Fnom, 0.0, 0.0, 0.0, 0.0, Vnom), _p4_M111)

    @test out.Rl  < _p4_p61.unloaded_radius
    @test out.Re  < _p4_p61.unloaded_radius
    @test out.rho > 0.0
    @test out.Kxk > 0.0
    @test out.Kya != 0.0
end

@testset "Phase 4: invariants — all three MF versions" begin
    for (label, tp) in (("MF6.1", _p4_p61), ("MF6.2", _p4_p62), ("MF5.2", _p4_p52))
        @testset "$label" begin
            out = mfeval(tp, MFInputs(tp.fnomin, 0.0, 0.1, 0.0, 0.0, tp.longvl), _p4_M111)
            @test all(isfinite, to_vector(out))
            @test out.Rl  < tp.unloaded_radius
            @test out.rho > 0.0
            @test out.Kxk > 0.0
        end
    end
end

@testset "Phase 4: invariants — Fy sign antisymmetry under alpha flip" begin
    # sign(Fy(+alpha)) must equal -sign(Fy(-alpha)) at zero camber
    Fnom = _p4_p61.fnomin
    Vnom = _p4_p61.longvl
    for alpha in (0.05, 0.10, 0.20, 0.30)
        op = mfeval(_p4_p61, MFInputs(Fnom, 0.0,  alpha, 0.0, 0.0, Vnom), _p4_M111)
        on = mfeval(_p4_p61, MFInputs(Fnom, 0.0, -alpha, 0.0, 0.0, Vnom), _p4_M111)
        @test sign(op.Fy) == -sign(on.Fy)
        # Asymmetry (from SVy offset) must be < 30% of signal
        asymmetry = abs(op.Fy + on.Fy)
        magnitude = 0.5 * (abs(op.Fy) + abs(on.Fy))
        @test asymmetry < 0.30 * magnitude
    end
end

@testset "Phase 4: invariants — Fx sign antisymmetry under kappa flip" begin
    Fnom = _p4_p61.fnomin
    Vnom = _p4_p61.longvl
    for kappa in (0.05, 0.10, 0.20)
        op = mfeval(_p4_p61, MFInputs(Fnom,  kappa, 0.0, 0.0, 0.0, Vnom), _p4_M111)
        on = mfeval(_p4_p61, MFInputs(Fnom, -kappa, 0.0, 0.0, 0.0, Vnom), _p4_M111)
        @test sign(op.Fx) == -sign(on.Fx)
    end
end

# ==============================================================================
# D) BATCH vs SCALAR CONSISTENCY
# ==============================================================================

@testset "Phase 4: batch vs scalar — Fz x alpha grid (5x5)" begin
    Fnom   = _p4_p61.fnomin
    Vnom   = _p4_p61.longvl
    Fzs    = [0.5, 0.75, 1.0, 1.5, 2.0] .* Fnom
    alphas = [-0.2, -0.1, 0.0, 0.1, 0.2]
    N      = length(Fzs) * length(alphas)

    mat = Matrix{Float64}(undef, N, 6)
    k = 1
    for Fz in Fzs, alpha in alphas
        mat[k, :] = [Fz, 0.0, alpha, 0.0, 0.0, Vnom]
        k += 1
    end

    batch = mfeval(_p4_p61, mat, _p4_M111)

    for i in 1:N
        inp   = MFInputs(mat[i,1], mat[i,2], mat[i,3], mat[i,4], mat[i,5], mat[i,6])
        sv    = to_vector(mfeval(_p4_p61, inp, _p4_M111))
        row_b = vcat(batch[i, 1:28], [batch[i, 30]])
        row_s = vcat(sv[1:28],       [sv[30]])
        @test row_b ≈ row_s  atol=1e-9
    end
end

@testset "Phase 4: batch vs scalar — kappa x alpha grid (5x5)" begin
    Fnom   = _p4_p61.fnomin
    Vnom   = _p4_p61.longvl
    kappas = [-0.2, -0.1, 0.0, 0.1, 0.2]
    alphas = [-0.15, -0.05, 0.0, 0.05, 0.15]
    N      = length(kappas) * length(alphas)

    mat = Matrix{Float64}(undef, N, 6)
    k = 1
    for kappa in kappas, alpha in alphas
        mat[k, :] = [Fnom, kappa, alpha, 0.0, 0.0, Vnom]
        k += 1
    end

    batch = mfeval(_p4_p61, mat, _p4_M111)

    for i in 1:N
        inp   = MFInputs(mat[i,1], mat[i,2], mat[i,3], mat[i,4], mat[i,5], mat[i,6])
        sv    = to_vector(mfeval(_p4_p61, inp, _p4_M111))
        row_b = vcat(batch[i, 1:28], [batch[i, 30]])
        row_s = vcat(sv[1:28],       [sv[30]])
        @test row_b ≈ row_s  atol=1e-9
    end
end
